// Auto-generated by mkindex.sh — do not edit
export default [
  "01 - Perpetual Overload.mp3",
  "06 - 3 Body Problem.mp3",
  "08 - Industrial Dreams.mp3",
  "12 - Between The Worlds.mp3",
  "17 - Neural Networks.mp3",
  "18 - Sounds Of Infinity.mp3",
  "80's Synthwave by MOKKA - Synthetic Pleasures.mp3",
  "California Sunshine - The Gate To The Past (Remix).mp3",
  "preview-loop.mp3"
];
