// Auto-generated by measure-loudness.sh — do not edit
export default [
  { file: "01 - Perpetual Overload.mp3", gain: 0.619, duration: 173.0 },
  { file: "06 - 3 Body Problem.mp3", gain: 0.625, duration: 171.9 },
  { file: "08 - Industrial Dreams.mp3", gain: 0.591, duration: 171.4 },
  { file: "12 - Between The Worlds.mp3", gain: 0.662, duration: 144.9 },
  { file: "17 - Neural Networks.mp3", gain: 0.583, duration: 164.3 },
  { file: "18 - Sounds Of Infinity.mp3", gain: 0.653, duration: 184.9 },
  { file: "80's Synthwave by MOKKA - Synthetic Pleasures.mp3", gain: 0.392, duration: 128.0 },
  { file: "California Sunshine - The Gate To The Past (Remix).mp3", gain: 0.649, duration: 430.0 },
  { file: "preview-loop.mp3", gain: 1.462, duration: 7.1 }
];
