#!/usr/bin/env bash
# Measure integrated loudness (EBU R128) and duration of every audio file
# listed in index.js and regenerate index.js with per-file gain/duration values.
#
# Requires: ffmpeg
# Usage:    cd web/media/audio && bash measure-loudness.sh
#           bash measure-loudness.sh --force   # re-measure all, ignore cached values

set -eo pipefail

FORCE=false
if [[ "${1:-}" == "--force" ]]; then FORCE=true; fi

TARGET_LUFS=-14   # target integrated loudness

# ── Parse file list + existing values from index.js ────────
files=()
declare -A existing_gains
declare -A existing_durations

while IFS= read -r line; do
  # Object entry:  { file: "song.mp3", gain: 1.234, duration: 180.5 },
  if [[ "$line" =~ file:\ *\"([^\"]*)\" ]]; then
    local_file="${BASH_REMATCH[1]}"
    files+=("$local_file")
    if [[ "$line" =~ gain:\ *([0-9.]+) ]]; then
      existing_gains["$local_file"]="${BASH_REMATCH[1]}"
    fi
    if [[ "$line" =~ duration:\ *([0-9.]+) ]]; then
      existing_durations["$local_file"]="${BASH_REMATCH[1]}"
    fi
  # Plain string entry:  "song.mp3",
  elif [[ "$line" =~ \"([^\"]+\.(mp3|ogg|wav|flac))\" ]]; then
    files+=("${BASH_REMATCH[1]}")
  fi
done < index.js

echo "Found ${#files[@]} tracks (${#existing_gains[@]} already measured)."
echo ""

# ── Measure each file ─────────────────────────────────────
declare -A gains
declare -A durations

for f in "${files[@]}"; do
  # Re-use existing values if already measured (unless --force)
  if [[ "$FORCE" == "false" && -n "${existing_gains[$f]+x}" && -n "${existing_durations[$f]+x}" ]]; then
    gains["$f"]="${existing_gains[$f]}"
    durations["$f"]="${existing_durations[$f]}"
    echo "CACHED: $f  →  gain: ${existing_gains[$f]}  dur: ${existing_durations[$f]}s"
    continue
  fi
  if [[ ! -f "$f" ]]; then
    echo "SKIP (not found): $f"
    gains["$f"]="1.0"
    durations["$f"]="0"
    continue
  fi

  # Get duration via ffprobe
  dur_secs=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$f" 2>/dev/null || echo "0")
  dur_secs=$(printf "%.1f" "$dur_secs")

  # Measure EBU R128 integrated loudness
  lufs=$(ffmpeg -i "$f" -af loudnorm=print_format=json -f null - 2>&1 \
    | grep '"input_i"' \
    | head -1 \
    | sed 's/.*: *"\([^"]*\)".*/\1/')

  if [[ -z "$lufs" || "$lufs" == "-inf" ]]; then
    echo "SKIP (silent): $f"
    gains["$f"]="1.0"
    durations["$f"]="$dur_secs"
    continue
  fi

  # gain_db = target - measured;  gain_linear = 10^(gain_db/20)
  gain_db=$(echo "$TARGET_LUFS - ($lufs)" | bc -l)
  gain_linear=$(echo "e($gain_db / 20 * l(10))" | bc -l)

  # Clamp to 3 decimal places
  gain_linear=$(printf "%.3f" "$gain_linear")

  echo "$f  →  ${lufs} LUFS  →  gain: ${gain_linear}  dur: ${dur_secs}s"
  gains["$f"]="$gain_linear"
  durations["$f"]="$dur_secs"
done

# ── Write new index.js ─────────────────────────────────────
{
  echo "// Auto-generated by measure-loudness.sh — do not edit"
  echo "export default ["

  last_idx=$(( ${#files[@]} - 1 ))
  for i in "${!files[@]}"; do
    f="${files[$i]}"
    g="${gains[$f]}"
    d="${durations[$f]}"
    comma=","
    if (( i == last_idx )); then comma=""; fi
    printf '  { file: "%s", gain: %s, duration: %s }%s\n' "$f" "$g" "$d" "$comma"
  done

  echo "];"
} > index.js

echo ""
echo "✓ index.js updated with per-track gain and duration values."
