#!/usr/bin/env bash
# Regenerate index.js with all .ahx files found recursively.
# Usage:  cd media/ahx && bash generate-index.sh
set -eo pipefail

files=()
while IFS= read -r -d '' path; do
  rel="${path#./}"
  files+=("$rel")
done < <(find . -type f -iname '*.ahx' -print0 | sort -z)

echo "Found ${#files[@]} AHX files."

{
  echo "// Auto-generated by generate-index.sh — do not edit"
  echo "export default ["
  for f in "${files[@]}"; do
    # Escape double-quotes and backslashes in filenames
    safe="${f//\\/\\\\}"
    safe="${safe//\"/\\\"}"
    echo "  { file: \"${safe}\" },"
  done
  echo "];"
} > index.js

echo "Wrote index.js (${#files[@]} entries)."
