// Auto-generated by mkindex.sh — do not edit
export default [
  "0d6e8963-65e5-4ada-9b22-27f23513f9b5.jpg",
  "dark-wood-stain_albedo.png",
  "granite-gray-white-height.png",
  "rock_surface.png",
  "texturelabs_wood_1895.jpg",
  "titanium-scuffed_metallic.png"
];
