#!/usr/bin/env bash
# Index all image files with their dimensions, auto-discovering files on disk.
#
# Requires: sips (macOS built-in) or identify (ImageMagick)
# Usage:    cd web/media/textures && bash measure-textures.sh

set -eo pipefail

# ── Auto-discover all image files in current dir and subdirs
files=()
while IFS= read -r -d '' path; do
  rel="${path#./}"
  files+=("$rel")
done < <(find . -maxdepth 2 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.gif' -o -iname '*.bmp' \) ! -name '.*' -print0 | sort -z)

echo "Found ${#files[@]} images."
echo ""

# ── Parse existing dimensions from index.js (cache)
declare -A existing_widths
declare -A existing_heights

if [[ -f index.js ]]; then
  while IFS= read -r line; do
    if [[ "$line" =~ file:\ *\"([^\"]*)\" ]]; then
      local_file="${BASH_REMATCH[1]}"
      if [[ "$line" =~ width:\ *([0-9]+) ]]; then
        existing_widths["$local_file"]="${BASH_REMATCH[1]}"
      fi
      if [[ "$line" =~ height:\ *([0-9]+) ]]; then
        existing_heights["$local_file"]="${BASH_REMATCH[1]}"
      fi
    fi
  done < index.js
fi

# ── Measure each image
declare -A widths
declare -A heights

for f in "${files[@]}"; do
  # Use cached values if available
  if [[ -n "${existing_widths[$f]+x}" && -n "${existing_heights[$f]+x}" ]]; then
    widths["$f"]="${existing_widths[$f]}"
    heights["$f"]="${existing_heights[$f]}"
    echo "CACHED: $f  →  ${existing_widths[$f]}×${existing_heights[$f]}"
    continue
  fi

  if [[ ! -f "$f" ]]; then
    echo "SKIP (not found): $f"
    widths["$f"]="0"
    heights["$f"]="0"
    continue
  fi

  # Get dimensions via sips (macOS) or identify (ImageMagick)
  if command -v sips &>/dev/null; then
    w=$(sips -g pixelWidth "$f" 2>/dev/null | awk '/pixelWidth/{print $2}')
    h=$(sips -g pixelHeight "$f" 2>/dev/null | awk '/pixelHeight/{print $2}')
  elif command -v identify &>/dev/null; then
    dims=$(identify -format "%w %h" "$f" 2>/dev/null)
    w=$(echo "$dims" | awk '{print $1}')
    h=$(echo "$dims" | awk '{print $2}')
  else
    echo "ERROR: need sips (macOS) or identify (ImageMagick)"
    exit 1
  fi

  widths["$f"]="${w:-0}"
  heights["$f"]="${h:-0}"
  echo "$f  →  ${w:-0}×${h:-0}"
done

# ── Write new index.js
{
  echo "// Auto-generated by measure-textures.sh — do not edit"
  echo "export default ["

  last_idx=$(( ${#files[@]} - 1 ))
  for i in "${!files[@]}"; do
    f="${files[$i]}"
    w="${widths[$f]}"
    h="${heights[$f]}"
    comma=","
    if (( i == last_idx )); then comma=""; fi
    printf '  { file: "%s", width: %s, height: %s }%s\n' "$f" "$w" "$h" "$comma"
  done

  echo "];"
} > index.js

echo ""
echo "✓ index.js updated with per-image dimensions."
