// Auto-generated by measure-textures.sh — do not edit
export default [
  { file: "dark-wood-stain_albedo.png", width: 1024, height: 1024 },
  { file: "granite-gray-white-height.png", width: 1024, height: 1024 },
  { file: "rock_surface.png", width: 1024, height: 1024 },
  { file: "texturelabs_wood_1895.jpg", width: 1024, height: 1024 },
  { file: "titanium-scuffed_metallic.png", width: 1024, height: 1024 }
];
