/**
 * Shader index — single source of truth for all available shaders.
 * Each entry: { path: relative to repo root index.html, name: display name }
 * Grouped by folder.
 */
const SHADER_INDEX = [
  {
    folder: "experimental",
    shaders: [
      { name: "Ball In Clouds", path: "web/shaders/experimental/ball-in-clouds.glsl" },
      { name: "Champions Ball 1", path: "web/shaders/experimental/champions-ball-1.glsl" },
      { name: "Champions Ball 2", path: "web/shaders/experimental/champions-ball-2.glsl" },
      { name: "Champions Ball 3", path: "web/shaders/experimental/champions-ball-3.glsl" },
      { name: "Champions Ball 4", path: "web/shaders/experimental/champions-ball-4.glsl" },
      { name: "Champions Ball 5", path: "web/shaders/experimental/champions-ball-5.glsl" },
      { name: "Chrome Spectrum", path: "web/shaders/experimental/chrome-spectrum.glsl" },
      { name: "Lipstick Dancers", path: "web/shaders/experimental/lipstick-dancers.glsl" },
      { name: "Meteor Ball", path: "web/shaders/experimental/meteor-ball.glsl" },
      { name: "Meteors", path: "web/shaders/experimental/meteors.glsl" },
      { name: "Plasma Pixels", path: "web/shaders/experimental/plasma-pixels.glsl" },
      { name: "Plasma", path: "web/shaders/experimental/plasma.glsl" },
      { name: "Polyhedron Test", path: "web/shaders/experimental/polyhedron-test.glsl" },
      { name: "Sliding Waves", path: "web/shaders/experimental/sliding-waves.glsl" },
      { name: "Starry Ball", path: "web/shaders/experimental/starry-ball.glsl" },
    ],
  },
  {
    folder: "restricted",
    shaders: [
      { name: "Chrome Spectrum", path: "web/shaders/restricted/chrome-spectrum.glsl" },
      { name: "Chrome Spectrum1", path: "web/shaders/restricted/chrome-spectrum1.glsl" },
      { name: "Chrome Spectrum2", path: "web/shaders/restricted/chrome-spectrum2.glsl" },
      { name: "Cubescape Alt", path: "web/shaders/restricted/cubescape-alt.glsl" },
      { name: "Cubescape", path: "web/shaders/restricted/cubescape.glsl" },
    ],
  },
  {
    folder: "shadertoy",
    shaders: [
      { name: "Bands Remix", path: "web/shaders/shadertoy/bands-remix.glsl" },
      { name: "Blue Red Shiny 2", path: "web/shaders/shadertoy/blue-red-shiny-2.glsl" },
      { name: "Colourful Reactive Ribbons", path: "web/shaders/shadertoy/colourful-reactive-ribbons.glsl" },
      { name: "Creation By Silexars", path: "web/shaders/shadertoy/creation-by-silexars.glsl" },
      { name: "Cyberspace Data Warehouse Ar", path: "web/shaders/shadertoy/cyberspace-data-warehouse-ar.glsl" },
      { name: "Disco Sun Vortex", path: "web/shaders/shadertoy/disco-sun-vortex.glsl" },
      { name: "Floating Ribbons", path: "web/shaders/shadertoy/floating-ribbons.glsl" },
      { name: "Flowing Ribbons", path: "web/shaders/shadertoy/flowing-ribbons.glsl" },
      { name: "Iridescent Ribbons", path: "web/shaders/shadertoy/iridescent-ribbons.glsl" },
      { name: "Kaos Kutuları", path: "web/shaders/shadertoy/kaos-kutuları.glsl" },
      { name: "Kuantum Dalgalanmaları", path: "web/shaders/shadertoy/kuantum-dalgalanmaları.glsl" },
      { name: "Pattern 007 Ripples", path: "web/shaders/shadertoy/pattern-007-ripples.glsl" },
      { name: "Renkli Evren 01", path: "web/shaders/shadertoy/renkli-evren-01.glsl" },
      { name: "Renkli Taşlar", path: "web/shaders/shadertoy/renkli-taşlar.glsl" },
      { name: "Ribbon Waves", path: "web/shaders/shadertoy/ribbon-waves.glsl" },
      { name: "Total Noob (loading Ring)", path: "web/shaders/shadertoy/total noob (loading ring).glsl" },
      { name: "Total Noob", path: "web/shaders/shadertoy/total-noob.glsl" },
      { name: "Turbulent Star", path: "web/shaders/shadertoy/turbulent-star.glsl" },
      { name: "Vertical Ribbon", path: "web/shaders/shadertoy/vertical-ribbon.glsl" },
      { name: "Year Of Truchets 038", path: "web/shaders/shadertoy/year-of-truchets-038.glsl" },
    ],
  },
  {
    folder: "shadertoy-gpu-audio",
    shaders: [
      { name: "Audio Library Test+visual", path: "web/shaders/shadertoy-gpu-audio/audio-library-test+visual.glsl" },
      { name: "Frozen Wasteland", path: "web/shaders/shadertoy-gpu-audio/frozen-wasteland.glsl" },
      { name: "Sound Acid Jam", path: "web/shaders/shadertoy-gpu-audio/sound-acid-jam.glsl" },
      { name: "Stardust", path: "web/shaders/shadertoy-gpu-audio/stardust.glsl" },
      { name: "Xyptonjtroz", path: "web/shaders/shadertoy-gpu-audio/xyptonjtroz.glsl" },
    ],
  },
  {
    folder: "xordev",
    shaders: [
      { name: "3d Fire", path: "web/shaders/xordev/3d-fire.glsl" },
      { name: "Accelerator", path: "web/shaders/xordev/accelerator.glsl" },
      { name: "Accretion", path: "web/shaders/xordev/accretion.glsl" },
      { name: "Ancient Alien Cathedral Tunnal", path: "web/shaders/xordev/ancient-alien-cathedral-tunnal.glsl" },
      { name: "Blackhole", path: "web/shaders/xordev/blackhole.glsl" },
      { name: "Caustics", path: "web/shaders/xordev/caustics.glsl" },
      { name: "Cloudy Planet", path: "web/shaders/xordev/cloudy-planet.glsl" },
      { name: "Complementary Flow Adjusted", path: "web/shaders/xordev/complementary-flow-adjusted.glsl" },
      { name: "Falls", path: "web/shaders/xordev/falls.glsl" },
      { name: "Ghosts", path: "web/shaders/xordev/ghosts.glsl" },
      { name: "Global", path: "web/shaders/xordev/global.glsl" },
      { name: "Ionize", path: "web/shaders/xordev/ionize.glsl" },
      { name: "Jetstream", path: "web/shaders/xordev/jetstream.glsl" },
      { name: "Maelstrom", path: "web/shaders/xordev/maelstrom.glsl" },
      { name: "Milky", path: "web/shaders/xordev/milky.glsl" },
      { name: "Minecraft Tunnel", path: "web/shaders/xordev/minecraft-tunnel.glsl" },
      { name: "Missiles", path: "web/shaders/xordev/missiles.glsl" },
      { name: "Neural", path: "web/shaders/xordev/neural.glsl" },
      { name: "Nova", path: "web/shaders/xordev/nova.glsl" },
      { name: "Parametrics", path: "web/shaders/xordev/parametrics.glsl" },
      { name: "Plasma Globe", path: "web/shaders/xordev/plasma-globe.glsl" },
      { name: "Quasar 2", path: "web/shaders/xordev/quasar-2.glsl" },
      { name: "Revive", path: "web/shaders/xordev/revive.glsl" },
      { name: "Shield", path: "web/shaders/xordev/shield.glsl" },
      { name: "Shiny Disk", path: "web/shaders/xordev/shiny-disk.glsl" },
      { name: "Simple Neon Lines", path: "web/shaders/xordev/simple-neon-lines.glsl" },
      { name: "Spellbound", path: "web/shaders/xordev/spellbound.glsl" },
      { name: "Stellar", path: "web/shaders/xordev/stellar.glsl" },
      { name: "String Theory", path: "web/shaders/xordev/string-theory.glsl" },
      { name: "Surf 2", path: "web/shaders/xordev/surf-2.glsl" },
      { name: "Tonemapping Rings 2", path: "web/shaders/xordev/tonemapping-rings-2.glsl" },
      { name: "Tonemapping Rings", path: "web/shaders/xordev/tonemapping-rings.glsl" },
      { name: "Torus Glossy", path: "web/shaders/xordev/torus-glossy.glsl" },
      { name: "Torus Textured", path: "web/shaders/xordev/torus-textured.glsl" },
      { name: "Vortex 2", path: "web/shaders/xordev/vortex-2.glsl" },
      { name: "Vortex", path: "web/shaders/xordev/vortex.glsl" },
    ],
  },
];

export default SHADER_INDEX;
