/**
 * Shader index — single source of truth for all available shaders.
 * Each entry: { path: relative to repo root index.html, name: display name }
 * Grouped by folder.
 */
const SHADER_INDEX = [
  {
    folder: "experimental",
    shaders: [
      { name: "Champions Ball 0", path: "web/shaders/experimental/champions-ball-0.glsl" },
      { name: "Champions Ball 1", path: "web/shaders/experimental/champions-ball-1.glsl" },
      { name: "Champions Ball 2", path: "web/shaders/experimental/champions-ball-2.glsl" },
      { name: "Champions Ball 3", path: "web/shaders/experimental/champions-ball-3.glsl" },
      { name: "Champions Ball 4", path: "web/shaders/experimental/champions-ball-4.glsl" },
      { name: "Champions Ball 5", path: "web/shaders/experimental/champions-ball-5.glsl" },
      { name: "Champions Ball 6", path: "web/shaders/experimental/champions-ball-6.glsl" },
      { name: "Meteor Ball", path: "web/shaders/experimental/meteor-ball.glsl" },
      { name: "Plasma Grid", path: "web/shaders/experimental/plasma-grid.glsl" },
      { name: "Plasma", path: "web/shaders/experimental/plasma.glsl" },
      { name: "Sliding Waves", path: "web/shaders/experimental/sliding-waves.glsl" },
      { name: "Sparkling Tail", path: "web/shaders/experimental/sparkling-tail.glsl" },
    ],
  },
  {
    folder: "shadertoy",
    shaders: [
      { name: "Bands Remix", path: "web/shaders/shadertoy/bands-remix.glsl" },
      { name: "Blue Red Shiny 2", path: "web/shaders/shadertoy/blue-red-shiny-2.glsl" },
      { name: "Colorful Reactive Ribbons", path: "web/shaders/shadertoy/colorful-reactive-ribbons.glsl" },
      { name: "Floating Ribbons", path: "web/shaders/shadertoy/floating-ribbons.glsl" },
      { name: "Flowing Ribbons", path: "web/shaders/shadertoy/flowing-ribbons.glsl" },
      { name: "Irridescent Ribbons", path: "web/shaders/shadertoy/irridescent-ribbons.glsl" },
      { name: "Ribbon Waves", path: "web/shaders/shadertoy/ribbon-waves.glsl" },
      { name: "Total Noob (loading Ring)", path: "web/shaders/shadertoy/total noob (loading ring).glsl" },
      { name: "Total Noob", path: "web/shaders/shadertoy/total-noob.glsl" },
      { name: "Vertical Ribbon", path: "web/shaders/shadertoy/vertical-ribbon.glsl" },
    ],
  },
  {
    folder: "xordev",
    shaders: [
      { name: "3d Fire", path: "web/shaders/xordev/3d-fire.glsl" },
      { name: "Accelerator", path: "web/shaders/xordev/accelerator.glsl" },
      { name: "Accretion", path: "web/shaders/xordev/accretion.glsl" },
      { name: "Ancient Alien Cathedral Tunnal", path: "web/shaders/xordev/ancient-alien-cathedral-tunnal.glsl" },
      { name: "Blackhole", path: "web/shaders/xordev/blackhole.glsl" },
      { name: "Caustics", path: "web/shaders/xordev/caustics.glsl" },
      { name: "Cloudy Planet", path: "web/shaders/xordev/cloudy-planet.glsl" },
      { name: "Complementary Flow Adjusted", path: "web/shaders/xordev/complementary-flow-adjusted.glsl" },
      { name: "Falls", path: "web/shaders/xordev/falls.glsl" },
      { name: "Global", path: "web/shaders/xordev/global.glsl" },
      { name: "Ionize", path: "web/shaders/xordev/ionize.glsl" },
      { name: "Jetstream", path: "web/shaders/xordev/jetstream.glsl" },
      { name: "Maelstrom", path: "web/shaders/xordev/maelstrom.glsl" },
      { name: "Milky", path: "web/shaders/xordev/milky.glsl" },
      { name: "Minecraft Tunnel", path: "web/shaders/xordev/minecraft-tunnel.glsl" },
      { name: "Missiles", path: "web/shaders/xordev/missiles.glsl" },
      { name: "Neural", path: "web/shaders/xordev/neural.glsl" },
      { name: "Nova", path: "web/shaders/xordev/nova.glsl" },
      { name: "Parametrics", path: "web/shaders/xordev/parametrics.glsl" },
      { name: "Plasma Globe", path: "web/shaders/xordev/plasma-globe.glsl" },
      { name: "Quasar 2", path: "web/shaders/xordev/quasar-2.glsl" },
      { name: "Revive", path: "web/shaders/xordev/revive.glsl" },
      { name: "Shiny Disk", path: "web/shaders/xordev/shiny-disk.glsl" },
      { name: "Simple Neon Lines", path: "web/shaders/xordev/simple-neon-lines.glsl" },
      { name: "Spellbound", path: "web/shaders/xordev/spellbound.glsl" },
      { name: "Stellar", path: "web/shaders/xordev/stellar.glsl" },
      { name: "String Theory", path: "web/shaders/xordev/string-theory.glsl" },
      { name: "Surf 2", path: "web/shaders/xordev/surf-2.glsl" },
      { name: "Tonemapping Rings 2", path: "web/shaders/xordev/tonemapping-rings-2.glsl" },
      { name: "Tonemapping Rings", path: "web/shaders/xordev/tonemapping-rings.glsl" },
      { name: "Torus Glossy", path: "web/shaders/xordev/torus-glossy.glsl" },
      { name: "Torus Textured", path: "web/shaders/xordev/torus-textured.glsl" },
      { name: "Vortex 2", path: "web/shaders/xordev/vortex-2.glsl" },
      { name: "Vortex", path: "web/shaders/xordev/vortex.glsl" },
    ],
  },
];

export default SHADER_INDEX;
