#!/usr/bin/env bash
# Measure integrated loudness (EBU R128) and duration of every tracker file
# listed in index.js and regenerate index.js with per-file gain/duration values.
#
# Requires: openmpt123 (brew install libopenmpt), ffmpeg
# Usage:    cd web/media/mod && bash measure-loudness.sh
#           bash measure-loudness.sh --force   # re-measure all, ignore cached gains

set -eo pipefail

FORCE=false
if [[ "${1:-}" == "--force" ]]; then FORCE=true; fi

TARGET_LUFS=-14   # target integrated loudness

TMPDIR_RENDER=$(mktemp -d)
trap 'rm -rf "$TMPDIR_RENDER"' EXIT

# ── Parse file list + existing gains/durations from index.js
files=()
declare -A existing_gains
declare -A existing_durations

while IFS= read -r line; do
  # Object entry:  { file: "trance/foo.xm", gain: 1.234, duration: 71.7 },
  if [[ "$line" =~ file:\ *\"([^\"]*)\" ]]; then
    local_file="${BASH_REMATCH[1]}"
    files+=("$local_file")
    if [[ "$line" =~ gain:\ *([0-9.]+) ]]; then
      existing_gains["$local_file"]="${BASH_REMATCH[1]}"
    fi
    if [[ "$line" =~ duration:\ *([0-9.]+) ]]; then
      existing_durations["$local_file"]="${BASH_REMATCH[1]}"
    fi
  # Plain string entry:  "trance/foo.xm",
  elif [[ "$line" =~ \"([^\"]+\.(mod|xm|s3m|it))\" ]]; then
    files+=("${BASH_REMATCH[1]}")
  fi
done < index.js

echo "Found ${#files[@]} tracks (${#existing_gains[@]} already measured)."
echo ""

# ── Measure each file ─────────────────────────────────────
declare -A gains
declare -A durations

for f in "${files[@]}"; do
  # Re-use existing values if already measured (unless --force)
  if [[ "$FORCE" == "false" && -n "${existing_gains[$f]+x}" && -n "${existing_durations[$f]+x}" ]]; then
    gains["$f"]="${existing_gains[$f]}"
    durations["$f"]="${existing_durations[$f]}"
    echo "CACHED: $f  →  gain: ${existing_gains[$f]}  dur: ${existing_durations[$f]}s"
    continue
  fi
  if [[ ! -f "$f" ]]; then
    echo "SKIP (not found): $f"
    gains["$f"]="1.0"
    durations["$f"]="0"
    continue
  fi

  # Get duration from openmpt123 --info
  # Get duration from openmpt123 --info (format: "Duration...: MM:SS.mmm")
  dur_str=$(openmpt123 --info "$f" 2>&1 | grep '^Duration' | grep -oE '[0-9]+:[0-9]+\.[0-9]+')
  # Parse MM:SS.mmm → seconds
  if [[ "$dur_str" =~ ([0-9]+):([0-9.]+) ]]; then
    dur_secs=$(echo "${BASH_REMATCH[1]} * 60 + ${BASH_REMATCH[2]}" | bc -l)
    dur_secs=$(printf "%.1f" "$dur_secs")
  else
    dur_secs="0"
  fi

  # Render to WAV in temp dir
  wav_file="$TMPDIR_RENDER/render.wav"
  rm -f "$wav_file"

  openmpt123 --batch --quiet --force -o "$wav_file" "$f" 2>/dev/null

  if [[ ! -f "$wav_file" ]]; then
    echo "SKIP (render failed): $f"
    gains["$f"]="1.0"
    durations["$f"]="$dur_secs"
    continue
  fi

  # Measure EBU R128 integrated loudness
  lufs=$(ffmpeg -i "$wav_file" -af loudnorm=print_format=json -f null - 2>&1 \
    | grep '"input_i"' \
    | head -1 \
    | sed 's/.*: *"\([^"]*\)".*/\1/')

  if [[ -z "$lufs" || "$lufs" == "-inf" ]]; then
    echo "SKIP (silent): $f"
    gains["$f"]="1.0"
    durations["$f"]="$dur_secs"
    rm -f "$wav_file"
    continue
  fi

  # gain_db = target - measured;  gain_linear = 10^(gain_db/20)
  gain_db=$(echo "$TARGET_LUFS - ($lufs)" | bc -l)
  gain_linear=$(echo "e($gain_db / 20 * l(10))" | bc -l)

  # Clamp to 3 decimal places
  gain_linear=$(printf "%.3f" "$gain_linear")

  echo "$f  →  ${lufs} LUFS  →  gain: ${gain_linear}  dur: ${dur_secs}s"
  gains["$f"]="$gain_linear"
  durations["$f"]="$dur_secs"
  rm -f "$wav_file"
done

# ── Write new index.js ─────────────────────────────────────
{
  echo "// Auto-generated by measure-loudness.sh — do not edit"
  echo "export default ["

  last_idx=$(( ${#files[@]} - 1 ))
  for i in "${!files[@]}"; do
    f="${files[$i]}"
    g="${gains[$f]}"
    comma=","
    if (( i == last_idx )); then comma=""; fi
    d="${durations[$f]}"
    printf '  { file: "%s", gain: %s, duration: %s }%s\n' "$f" "$g" "$d" "$comma"
  done

  echo "];"
} > index.js

echo ""
echo "✓ index.js updated with per-track gain values."
